CREATE DATABASE IF NOT EXISTS icecysoap;
USE icecysoap;
CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(50) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, role ENUM('admin','dj') NOT NULL);
CREATE TABLE songs (id INT PRIMARY KEY AUTO_INCREMENT, file VARCHAR(255), tags TEXT, play_count INT DEFAULT 0, last_played DATETIME);
CREATE TABLE playlists (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), song_ids TEXT);
CREATE TABLE schedule (id INT PRIMARY KEY AUTO_INCREMENT, playlist_id INT, start_time DATETIME, end_time DATETIME);
CREATE TABLE logs (id INT PRIMARY KEY AUTO_INCREMENT, type VARCHAR(50), message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
